server:
  servlet:
    context-path: /apis
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jinchanchan
    username: root
    password: 242859
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 242859